name: ChaosCenter E2E testing

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main 

jobs:
  run-litmus:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        AccessType: [Ingress, LoadBalancer]
    env:
      TAG: "v3.7.0"  # Example tag, replace with appropriate value
      SELF_AGENT: "litmus-cluster"
      NS_MODE_NAMESPACE: "litmus"
    
    steps:
      - uses: actions/checkout@v2

      - uses: AbsaOSS/k3d-action@v2
        name: Create k8s Cluster
        with:
          cluster-name: ${{ env.SELF_AGENT }}
          k3d-version: v5.2.2
          args: >
            --agents 3
            --k3s-arg "--no-deploy=traefik, metrics-server@server:*"

      - name: Configuring and Testing the Cluster Installation
        run: |
          kubectl cluster-info --context k3d-${{ env.SELF_AGENT }}
          kubectl get nodes
          kubectl get pods -n kube-system
          
      - name: Deploying Litmus-Portal using k8s-manifest
        run: |
          chmod 755 ./litmus/install-portal.sh
          ./litmus/install-portal.sh
        env:
          PORTAL_VERSION: ${{ env.TAG }}
          ACCESS_TYPE: ${{ matrix.AccessType }}
          NAMESPACE: ${{ env.NS_MODE_NAMESPACE }}
          INSTALLATION_MODE: "NS-MODE"
          DEPLOY_SELF_AGENT: "false"

      - name: Set Cypress baseUrl
        run: echo "CYPRESS_baseUrl=${URL}" >> $GITHUB_ENV

      - name: Cypress run with env
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          working-directory: chaoscenter
